export const materials = [
  {
    firstName: 'Ron',
    lastName: 'Swanson',
    email: 'ron.swanson@gmail.com',
    phone: '452-123-2394',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Dec 15 2019'),
  },
  {
    firstName: 'Amy',
    lastName: 'Reed',
    email: 'amy.reed@gmail.com',
    phone: '293-158-2018',
    address: '201 Ashton Ave.',
    city: 'Thamesford',
    postal: 'U0S 3J2',
    manureType: 'cow',
    quantity: '150',
    organicSystem: false,
    composted: false,
    analysisAvailable: true,
    logisticsComments: null,
    deliveryAvailable: true,
    applicationAvailable: true,
    createdAt: new Date('Jan 01 2020'),
  },
  {
    firstName: 'Phil',
    lastName: 'Wilton',
    email: 'phil.wilton@gmail.com',
    phone: '928-927-4284',
    address: '100 Folsom St.',
    city: 'Belmont',
    postal: 'N0P 4I1',
    manureType: 'cow',
    quantity: '700',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: 'Only available until Springtime',
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 11 2020'),
  },
];

export const requests = [
  {
    firstName: 'Elliot',
    lastName: 'Rhodes',
    email: 'elliot.rhodes@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 03 2020'),
  },
  {
    firstName: 'Jake',
    lastName: 'Sloan',
    email: 'jake.sloan@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 09 2020'),
  },
  {
    firstName: 'Rob',
    lastName: 'Foster',
    email: 'rob.foster@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 12 2020'),
  },
  {
    firstName: 'Jane',
    lastName: 'Finch',
    email: 'jane.finch@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 15 2020'),
  },
  {
    firstName: 'Eric',
    lastName: 'Knope',
    email: 'eric.knope@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Jan 31 2020'),
  },
  {
    firstName: 'John',
    lastName: 'Elliot',
    email: 'john.elliot@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Feb 03 2020'),
  },
  {
    firstName: 'Ann',
    lastName: 'Harris',
    email: 'ann.harris@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Feb 04 2020'),
  },
  {
    firstName: 'Mary',
    lastName: 'Green',
    email: 'mary.green@gmail.com',
    phone: '829-928-2172',
    address: '1940 Main St.',
    city: 'Woodstock',
    postal: 'M6G 3T6',
    manureType: 'swine',
    quantity: '50',
    organicSystem: true,
    composted: false,
    analysisAvailable: false,
    logisticsComments: null,
    deliveryAvailable: false,
    applicationAvailable: false,
    createdAt: new Date('Feb 06 2020'),
  },
];
